export const dataZ = [
    {
        Category: "FRESHO",
        Name: "Apple",
        Image: require("../../assets/images/saved/fruits.png"),
        Gram: 500,
        Cost: 18,
        Offer: "40%",
        Strike: 25,
        rating: 3,
        id: 0,
    },
    {
        Category: "AASHIRVAAD",
        Name: "Wheat",
        Image: require("../../assets/images/saved/Foodgrains.png"),
        Gram: 1000,
        Cost: 39,
        Strike: 56,
        Offer: "50%",
        rating: 4,
        id: 1,
    },
    {
        Category: "NANDINI",
        Name: "Ghee",
        Image: require("../../assets/images/saved/Ghee.png"),
        Gram: 250,
        Cost: 108,
        Strike: 150,
        Offer: "20%",
        rating: 5,
        id: 2,
    },
    {
        Category: "LAYS",
        Name: "Chips",
        Image: require("../../assets/images/saved/chips.png"),
        Gram: 200,
        Cost: 10,
        Strike: 15,
        Offer: "30%",
        rating: 3,
        id: 3,
    }, {
        Category: "TOOTHPASTE",
        Name: "Pepsodent",
        Image: require("../../assets/images/saved/paste.png"),
        Gram: 200,
        Cost: 58,
        Strike: 75,
        Offer: "40%",
        rating: 2,
        id: 4,
    }, {
        Category: "OREO",
        Name: "Oreo Cream Biscuits",
        Image: require("../../assets/images/saved/Biscuit.png"),
        Gram: 1,
        Cost: 18,
        Strike: 25,
        Offer: "10%",
        rating: 4,
        id: 5,
    }, {
        Category: "LUX",
        Name: "Lux Soap",
        Image: require("../../assets/images/saved/Soap.png"),
        Gram: 1,
        Cost: 18,
        Strike: 25,
        Offer: "20%",
        rating: 3,
        id: 6,
    },
    {
        Category: "CHEESE",
        Name: "Britania Cheese",
        Image: require("../../assets/images/saved/cheese.png"),
        Gram: 500,
        Cost: 108,
        Strike: 150,
        Offer: "30%",
        rating: 2,
        id: 7,
    },
    {
        Category: "DRYFRUITS",
        Name: "Dryfruits",
        Image: require("../../assets/images/saved/dry.png"),
        Gram: 500,
        Cost: 18,
        Strike: 25,
        Offer: "60%",
        id: 8,
    },
    {
        Category: "BABYCARE",
        Name: "Johnson",
        Image: require("../../assets/images/saved/baby.png"),
        Gram: 500,
        Cost: 18,
        Strike: 25,
        Offer: "10%",
        rating: 5,
        id: 9
    },
    {
        Category: "EGGS",
        Name: "Eggs",
        Image: require("../../assets/images/saved/egg.png"),
        Gram: 500,
        Cost: 18,
        Strike: 25,
        rating: 4,
        Offer: "40%",
        id: 10
    },
    {
        Category: "EGGS",
        Name: "Eggs",
        Image: require("../../assets/images/saved/egg.png"),
        Gram: 500,
        Cost: 18,
        Strike: 25,
        Offer: "40%",
        rating: 5,
        id: 10
    }
]